### ISSUE TITLE
Expose data about what peers have downloaded what of your data

### ISSUE THREAD

**Issue by noffle** [kappa-db/multifeed#3]
This could be useful for apps that want to expose info like "5 peers have downloaded your latest message" or as a general measurement of data availability.

**Comment by 0fork** [comment]
So essentially recording replication events. One thing to keep in mind with this is that the stats shouldn’t be recorded into the hypercore that’s being measured (by default) because I’m guessing most people are not excited about exposing that sort of data. Also sharing content that’s not officially approved somewhere in the world might get you into trouble if somebody can just query how many times you have spread it. Given the copyright trolls roaming around this is a real concern even though stats are not exposing any identifying information.

**Comment by noffle** [comment]
+1 to keeping this data local. Or even just having multifeed emit events re this data, and let API consumers decide what to do with it.

**Comment by noffle** [comment]
I think this could be left as something implemented by another module, that watches the hypercores multifeed exposes to track the movement of blocks.
